/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c Gamedonia.jsb.ini" on 2013-03-20
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_GAMEDONIA

#import "OpenUDID.h"
#import "Gamedonia.h"
#import "GDDeviceProfile.h"
#import "GDSessionToken.h"
#import "GDUser.h"
#import "js_bindings_NS_manual.h"
JSB_GDSessionToken_createClass(_cx, Gamedonia, "SessionToken");
JSB_GamedoniaRequest_createClass(_cx, Gamedonia, "Request");
JSB_GDUserProfile_createClass(_cx, Gamedonia, "UserProfile");
JSB_GDUser_createClass(_cx, Gamedonia, "User");
JSB_GamedoniaScript_createClass(_cx, Gamedonia, "Script");
JSB_GamedoniaUsers_createClass(_cx, Gamedonia, "Users");
JSB_GamedoniaPush_createClass(_cx, Gamedonia, "Push");
JSB_Gamedonia_createClass(_cx, Gamedonia, "Gamedonia");
JSB_Credentials_createClass(_cx, Gamedonia, "Credentials");
JSB_OpenUDID_createClass(_cx, Gamedonia, "OpenUDID");
JSB_GamedoniaData_createClass(_cx, Gamedonia, "Data");
JSB_GamedoniaDevice_createClass(_cx, Gamedonia, "Device");
JSB_GDDeviceProfile_createClass(_cx, Gamedonia, "DeviceProfile");


#endif // JSB_INCLUDE_GAMEDONIA
