/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c Gamedonia.jsb.ini" on 2013-01-27
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_GAMEDONIA

#import "OpenUDID.h"
#import "Gamedonia.h"
#import "GDSessionToken.h"
#import "GDUser.h"
#import "js_bindings_NS_manual.h"

#import "jsfriendapi.h"
#import "js_bindings_config.h"
#import "js_bindings_core.h"
#import "js_bindings_basic_conversions.h"
#import "js_bindings_Gamedonia_functions.h"


#endif // JSB_INCLUDE_GAMEDONIA
