/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c Gamedonia.jsb.ini" on 2013-01-27
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_GAMEDONIA

#import "OpenUDID.h"
#import "Gamedonia.h"
#import "GDSessionToken.h"
#import "GDUser.h"
#import "js_bindings_NS_manual.h"
JSB_GDSessionToken_createClass(_cx, Gamedonia, "SessionToken");
JSB_GamedoniaRequest_createClass(_cx, Gamedonia, "Request");
JSB_GDUserProfile_createClass(_cx, Gamedonia, "UserProfile");
JSB_GDUser_createClass(_cx, Gamedonia, "User");
JSB_GamedoniaUsers_createClass(_cx, Gamedonia, "Users");
JSB_Gamedonia_createClass(_cx, Gamedonia, "Gamedonia");
JSB_Credentials_createClass(_cx, Gamedonia, "Credentials");
JSB_OpenUDID_createClass(_cx, Gamedonia, "OpenUDID");
JSB_GamedoniaData_createClass(_cx, Gamedonia, "Data");


#endif // JSB_INCLUDE_GAMEDONIA
