/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c Gamedonia.jsb.ini" on 2013-01-27
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_GAMEDONIA

#import "OpenUDID.h"
#import "Gamedonia.h"
#import "GDSessionToken.h"
#import "GDUser.h"
#import "js_bindings_NS_manual.h"

/*
 * GDSessionToken
 */
#pragma mark - GDSessionToken

#ifdef __cplusplus
extern "C" {
#endif

void JSB_GDSessionToken_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_GDSessionToken_object;
extern JSClass *JSB_GDSessionToken_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_GDSessionToken : JSB_NSObject
{
}
@end

/*
 * GDUserProfile
 */
#pragma mark - GDUserProfile

#ifdef __cplusplus
extern "C" {
#endif

void JSB_GDUserProfile_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_GDUserProfile_object;
extern JSClass *JSB_GDUserProfile_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_GDUserProfile : JSB_NSObject
{
}
@end

/*
 * GDUser
 */
#pragma mark - GDUser

#ifdef __cplusplus
extern "C" {
#endif

void JSB_GDUser_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_GDUser_object;
extern JSClass *JSB_GDUser_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_GDUser : JSB_GDUserProfile
{
}
@end

/*
 * Gamedonia
 */
#pragma mark - Gamedonia

#ifdef __cplusplus
extern "C" {
#endif

void JSB_Gamedonia_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_Gamedonia_object;
extern JSClass *JSB_Gamedonia_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_Gamedonia : JSB_NSObject
{
}
@end

/*
 * GamedoniaUsers
 */
#pragma mark - GamedoniaUsers

#ifdef __cplusplus
extern "C" {
#endif

void JSB_GamedoniaUsers_createClass(JSContext *cx, JSObject* globalObj, const char* name );

// Manually generated methods
JSBool JSB_GamedoniaUsers_createUser_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_loginUserWithGameCenterId_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_loginUserWithOpenUDID_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_loginUserWithEmail_password_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_loginUserWithFacebook_fbAccessToken_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_loginUserWithTwitter_twTokenSecret_twToken_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_loginUserWithSessionToken_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_logoutUser_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_getUser_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_getMe_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_updateUser_overwrite_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_changePassword_currentPassword_newPassword_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_resetPassword_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_restorePassword_newPassword_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaUsers_search_limit_sort_skip_callback_(JSContext *cx, uint32_t argc, jsval *vp);


extern JSObject *JSB_GamedoniaUsers_object;
extern JSClass *JSB_GamedoniaUsers_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_GamedoniaUsers : JSB_NSObject
{
}
@end

/*
 * GamedoniaRequest
 */
#pragma mark - GamedoniaRequest

#ifdef __cplusplus
extern "C" {
#endif

void JSB_GamedoniaRequest_createClass(JSContext *cx, JSObject* globalObj, const char* name );

// Manually generated methods
JSBool JSB_GamedoniaRequest_post_content_auth_sessionToken_gameid_success_failure__static(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaRequest_get_sessionToken_success_failure__static(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaRequest_put_content_auth_sessionToken_gameid_success_failure__static(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaRequest_del_success_failure__static(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaRequest_hmacsha1_secret__static(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaRequest_sign_secret_data_contentType_date_requestMethod_path__static(JSContext *cx, uint32_t argc, jsval *vp);


extern JSObject *JSB_GamedoniaRequest_object;
extern JSClass *JSB_GamedoniaRequest_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_GamedoniaRequest : JSB_NSObject
{
}
@end

/*
 * Credentials
 */
#pragma mark - Credentials

#ifdef __cplusplus
extern "C" {
#endif

void JSB_Credentials_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_Credentials_object;
extern JSClass *JSB_Credentials_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_Credentials : JSB_NSObject
{
}
@end

/*
 * OpenUDID
 */
#pragma mark - OpenUDID

#ifdef __cplusplus
extern "C" {
#endif

void JSB_OpenUDID_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_OpenUDID_object;
extern JSClass *JSB_OpenUDID_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_OpenUDID : JSB_NSObject
{
}
@end

/*
 * GamedoniaData
 */
#pragma mark - GamedoniaData

#ifdef __cplusplus
extern "C" {
#endif

void JSB_GamedoniaData_createClass(JSContext *cx, JSObject* globalObj, const char* name );

// Manually generated methods
JSBool JSB_GamedoniaData_create_entity_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaData_remove_entityId_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaData_update_entity_overwrite_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaData_get_entityId_callback_(JSContext *cx, uint32_t argc, jsval *vp);
JSBool JSB_GamedoniaData_search_query_limit_sort_skip_callback_(JSContext *cx, uint32_t argc, jsval *vp);


extern JSObject *JSB_GamedoniaData_object;
extern JSClass *JSB_GamedoniaData_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_GamedoniaData : JSB_NSObject
{
}
@end


#endif // JSB_INCLUDE_GAMEDONIA
