gd.AUTH_METHOD_SILENT		= 'SILENT'
gd.AUTH_METHOD_MAIL			= 'MAIL'
gd.AUTH_METHOD_FACEBOOK		= 'FACEBOOK'
gd.AUTH_METHOD_TWITTER		= 'TWITTER'
gd.AUTH_METHOD_GAMECENTER 	= 'GAMECENTER'

gd.API_KEYS_DEVELOPERS_NORMAL = 0;
gd.API_KEYS_DEVELOPERS_MASTER = 1;
gd.API_KEYS_PRODUCTION_NORMAL = 2;
gd.API_KEYS_PRODUCTION_MASTER = 3;

